---
channel : "ettt"
years_and_data_files:
  "2016_preVFP":
    - "SingleElectronB"
    - "SingleElectronC"
    - "SingleElectronD"
    - "SingleElectronE"
    - "SingleElectronF"
    - "TauB"
    - "TauC"
    - "TauD"
    - "TauE"
    - "TauF"
  "2016_postVFP":
    - "SingleElectronF"
    - "SingleElectronG"
    - "SingleElectronH"
    - "TauF"
    - "TauG"
    - "TauH"
  "2017":
    - "SingleElectronB"
    - "SingleElectronC"
    - "SingleElectronD"
    - "SingleElectronE"
    - "SingleElectronF"
    - "TauB"
    - "TauC"
    - "TauD"
    - "TauE"
    - "TauF"
  "2018":
    - "EGammaA"
    - "EGammaB"
    - "EGammaC"
    - "EGammaD"
    - "TauA"
    - "TauB"
    - "TauC"
    - "TauD"
years_and_mc_files:
  "2016_preVFP":
    - 'DYJetsToLL-LO'
    - 'DY1JetsToLL-LO'
    - 'DY2JetsToLL-LO'
    - 'DY3JetsToLL-LO'
    - 'DY4JetsToLL-LO'
    - 'DYJetsToLL_M-10to50-LO'
    - 'TTTo2L2Nu'
    - 'TTToHadronic'
    - 'TTToSemiLeptonic'
    - 'WZTo1L1Nu2Q'
    - 'WZTo3LNu'
    - 'WZTo3LNu'
    - 'WWTo2L2Nu'
    - 'ZZTo2L2Nu'
    - 'ZZTo4L'
    - 'T-tW'
    - 'Tbar-tW'
    - 'Tbar-t'
    - 'T-t'
    - 'WWZ'
    - 'WWZ-ext1'
    - 'WZZ'
    - 'WZZ-ext1'
    - 'WWW'
    - 'WWW-ext1'
    - 'ZZZ'
    - 'ZZZ-ext1'
    - 'WJetsToLNu-LO'
    - 'W1JetsToLNu-LO'
    - 'W2JetsToLNu-LO'
    - 'W3JetsToLNu-LO'
    - 'W4JetsToLNu-LO'
    - 'EWKWMinus2Jets_WToLNu'
    - 'EWKWPlus2Jets_WToLNu'
    - 'WGToLNuG'
    - 'GluGluToContinToZZTo2e2mu'
    - 'GluGluToContinToZZTo2e2tau'
    - 'GluGluToContinToZZTo2mu2tau'
    - 'GluGluToContinToZZTo4e'
    - 'GluGluToContinToZZTo4mu'
    - 'GluGluToContinToZZTo4tau'
  "2016_postVFP":
    - 'DYJetsToLL-LO'
    - 'DY1JetsToLL-LO'
    - 'DY2JetsToLL-LO'
    - 'DY3JetsToLL-LO'
    - 'DY4JetsToLL-LO'
    - 'DYJetsToLL_M-10to50-LO'
    - 'TTTo2L2Nu'
    - 'TTToHadronic'
    - 'TTToSemiLeptonic'
    - 'WZTo3LNu'
    - 'WZTo3LNu'
    - 'WWTo2L2Nu'
    - 'ZZTo2L2Nu'
    - 'ZZTo4L'
    - 'T-tW'
    - 'Tbar-tW'
    - 'Tbar-t'
    - 'T-t'
    - 'WWZ'
    - 'WWZ-ext1'
    - 'WZZ'
    - 'WZZ-ext1'
    - 'WWW'
    - 'WWW-ext1'
    - 'ZZZ'
    - 'ZZZ-ext1'
    - 'WJetsToLNu-LO'
    - 'W1JetsToLNu-LO'
    - 'W2JetsToLNu-LO'
    - 'W3JetsToLNu-LO'
    - 'W4JetsToLNu-LO'
    - 'EWKWMinus2Jets_WToLNu'
    - 'EWKWPlus2Jets_WToLNu'
    - 'WGToLNuG'
    - 'GluGluToContinToZZTo2e2mu'
    - 'GluGluToContinToZZTo2e2tau'
    - 'GluGluToContinToZZTo2mu2tau'
    - 'GluGluToContinToZZTo4e'
    - 'GluGluToContinToZZTo4mu'
    - 'GluGluToContinToZZTo4tau'
  "2017":
    - 'DYJetsToLL-LO'
    - 'DY1JetsToLL-LO'
    - 'DY2JetsToLL-LO'
    - 'DY3JetsToLL-LO'
    - 'DY4JetsToLL-LO'
    - 'DYJetsToLL_M-10to50-LO'
    - 'TTTo2L2Nu'
    - 'TTToHadronic'
    - 'TTToSemiLeptonic'
    - 'T-tW'
    - 'Tbar-tW'
    - 'Tbar-t'
    - 'T-t'
    - 'WZTo3LNu'
    - 'WWTo2L2Nu'
    - 'ZZTo2L2Nu'
    - 'ZZTo4L'
    - 'WWZ'
    - 'WWZ-ext1'
    - 'WZZ'
    - 'WZZ-ext1'
    - 'WWW'
    - 'WWW-ext1'
    - 'ZZZ'
    - 'ZZZ-ext1'
    - 'WJetsToLNu-LO'
    - 'W1JetsToLNu-LO'
    - 'W2JetsToLNu-LO'
    - 'W3JetsToLNu-LO'
    - 'W4JetsToLNu-LO'
    - 'EWKWMinus2Jets_WToLNu'
    - 'EWKWPlus2Jets_WToLNu'
    - 'WGToLNuG'
    - 'GluGluToContinToZZTo2e2mu'
    - 'GluGluToContinToZZTo2e2tau'
    - 'GluGluToContinToZZTo2mu2tau'
    - 'GluGluToContinToZZTo4e'
    - 'GluGluToContinToZZTo4mu'
    - 'GluGluToContinToZZTo4tau'
  "2018":
    - 'DYJetsToLL-LO'
    - 'DY1JetsToLL-LO'
    - 'DY2JetsToLL-LO'
    - 'DY3JetsToLL-LO'
    - 'DY4JetsToLL-LO'
    - 'DYJetsToLL_M-10to50-LO'
    - 'TTTo2L2Nu'
    - 'TTToHadronic'
    - 'TTToSemiLeptonic'
    - 'WZTo1L1Nu2Q'
    - 'WZTo3LNu'
    - 'WWTo1L1Nu2Q'
    - 'WWTo2L2Nu'
    - 'ZZTo2L2Nu'
    - 'ZZTo4L'
    - 'Tbar-t'
    - 'Tbar-tW'
    - 'T-t'
    - 'T-tW'
    - 'WWZ'
    - 'WWZ-ext1'
    - 'WZZ'
    - 'WZZ-ext1'
    - 'WWW'
    - 'WWW-ext1'
    - 'ZZZ'
    - 'ZZZ-ext1'
    - 'WJetsToLNu-LO'
    - 'W1JetsToLNu-LO'
    - 'W2JetsToLNu-LO'
    - 'W3JetsToLNu-LO'
    - 'W4JetsToLNu-LO'
    - 'EWKWMinus2Jets_WToLNu'
    - 'EWKWPlus2Jets_WToLNu'
    - 'WGToLNuG'
    - 'GluGluToContinToZZTo2e2mu'
    - 'GluGluToContinToZZTo2e2tau'
    - 'GluGluToContinToZZTo2mu2tau'
    - 'GluGluToContinToZZTo4e'
    - 'GluGluToContinToZZTo4mu'
    - 'GluGluToContinToZZTo4tau'
baseline_selection: "deepTauVsJets_iso_2>0.1 && deepTauVsJets_iso_3>0.1 && deepTauVsJets_iso_4>0.1 && iso_1<0.15 && deepTauVsMu_vloose_2>0.5 && deepTauVsEle_vvloose_2>0.5 && deepTauVsMu_vloose_3>0.5 && deepTauVsEle_vvloose_3>0.5 && deepTauVsMu_vloose_4>0.5 && deepTauVsEle_vvloose_4>0.5 && ((trg_singleelectron_1==1) || (trg_doubletau_23==1) || (trg_doubletau_24==1) || (trg_doubletau_34==1)) && (((isTau==1) && ((trg_singleelectron_1==1)))==0)"
pass_selection: "deepTauVsJets_loose_NUM"
sideband_pass: "q_sum==0"
alt_sideband_pass: "deepTauVsJets_loose_ALT"
mc_gen_match: "gen_match_NUM==6"
years_and_lumi:
  "2016_preVFP": 19520.0
  "2016_postVFP": 16810.0
  "2017": 41530.0 
  "2018": 59740.0
param_file: "/vols/cms/gu18/4tau_v3/CMSSW_10_2_19/src/UserCode/ICHiggsTauTau/Analysis/4tau/scripts/params_UL_YEAR.json"
mc_weight: "wt"
file_location: "/vols/cms/gu18/Offline/output/4tau/2301" 
file_ext: "_ettt_YEAR.root"
variables:
  - "tau_decay_mode_NUM"
  - "jet_pt_NUM/pt_NUM"
  - "pt_NUM"
  - "pt_NUM*cosh(eta_NUM)"
  - "n_jets"
  - "n_bjets"
  - "rho"
  - "mt_NUM"
  - "eta_NUM"
  - "q_NUM"
  - "trg_doubletau_leg_NUM"
  - "q_sum"
  - "deepTauVsJets_iso_ALT"
  - "YEAR"
